version: "3"
services: 
    airflow:
        image: puckel/docker-airflow
        container_name: "webservice"
        ports: 
            - "8080:8080"
        volumes: 
            - "./dags:/usr/local/airflow/dags"

